# conditions is to determine whether we can run the task or skip it
- name: Demo on conditions
  hosts: localhost
  connection: local
  tasks:
    - name: Print OS Redhat
      ansible.builtin.debug:
        msg: Redhat
      when: os == "redhat"

    - name: Print OS Ubuntu
      ansible.builtin.debug:
        msg: Ubuntu
      when: os == "ubuntu"

    - name: Print Even Number
      ansible.builtin.debug:
        msg: Number {{ number }} is even
      when: reminder == 0
      vars:
        reminder: "{{ number / 2 }}"



